### ISSUE TITLE
Retino conflicts with canvas' renderer engine.

### ISSUE THREAD

**Issue by Kichura** [juliand665/retiNO#1]
When combining the canvas-renderer mod with retino, Both mods end up conflicting from one or another class id and thous will cause the game to not work with it along.

https://pastebin.com/raw/aenqjmBL - The crash-report data,

https://pastebin.com/raw/P6aVi0KW - The latest.log data.

**Comment by juliand665** [comment]
Hmm, this might be due to me using `@Redirect` rather than `@Inject`, though the latter has since gained support for this situation. Can you try [this build](https://github.com/juliand665/retiNO/files/5721498/retino-1.0.1.jar.zip) and see if that fixes it?

**Comment by Kichura** [comment]
Tried this build with canvas combined and it has fixed this issue (Although canvas has since added a fix for macs to deal with resolution).

![image](https://user-images.githubusercontent.com/68134602/102725896-8a186f80-431a-11eb-9958-e65dc8dd6032.png)

**Comment by juliand665** [comment]
> canvas has since added a fix for macs to deal with resolution

Ah, that would also explain why there was a conflict lol, since we're probably both doing the same thing.
