### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by MoustacheOff** [juliand665/retiNO#3]
#### Now, we just need an update for Retino. 😄

**Comment by juliand665** [comment]
Chances are it already works! Could you try sticking the 1.18 jar in a 1.19 instance?

**Comment by MoustacheOff** [comment]
Okay, let me try…

**Comment by MoustacheOff** [comment]
Seems to work fine, however I don't have a Retina Mac to test it. (M1 Mac mini)

**Comment by juliand665** [comment]
Nice! Yeah, the mod is generally compatible across versions. I'll update CurseForge to reflect that it supports 1.19 :)
